config/routes.rb
Wodleader::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => 'pages#index'
  match '/competition/:competition' => 'pages#competition', :as => :competition

end

app/models/athlete.rb
class Athlete < ActiveRecord::Base
  belongs_to :competition
  has_many :event_athletes, :dependent => :destroy
  validates_presence_of :competition_id
  validates_presence_of :name
  belongs_to :competition_category
  validates_presence_of :competition_category
  
  after_create :create_event_athletes
  
  def max_ranking
    @max_ranking ||= Athlete.where("competition_id = #{self.competition_id}").count + 1
  end

  def category
    competition_category.name
  end

  def max_competition_ranking
    event_athletes.size * max_ranking
  end

  def competition_rank_total
    rank = 0
    event_athletes.each do |ea|
      if ea.event_rank
        event_ranking = (ea.event_rank * ea.event.event_weight)
        rank += event_ranking
      else
        rank += max_ranking
      end
    end
    rank
  end
  
  private
  
  def create_event_athletes
    competition.events.each do |event|
      ea = EventAthlete.new(:athlete_id => self.id, :event_id => event.id)
      ea.save
    end
  end
  
end

app/models/competition.rb
class Competition < ActiveRecord::Base
  has_many :events, :dependent => :destroy
  has_many :athletes, :dependent => :destroy
  validates_presence_of :name, :when, :where

  def leader_board
    leaders = {}
    athletes.each do |athlete|
      if leaders[athlete.category]
        leaders[athlete.category] << athlete
      else
        leaders[athlete.category] = [athlete]
      end
    end
    
    leaders.each do |category, athletes|
      leaders[category] = athletes.sort{|a,b| a.competition_rank_total <=> b.competition_rank_total}
    end
    leaders
  end
  
  def most_recent_stat_update
    event_ids = events.select{|event| event.id}
    recent = EventAthlete.where(:event_id => event_ids).order('updated_at DESC').first
    puts recent.inspect
    if recent
      recent.updated_at
    else
      nil
    end
  end
  
  def to_param
    "#{id}-#{name.downcase.gsub(/[^a-z0-9]+/,'-').gsub(/-+&$/, '').gsub(/^-+$/, '')}"
  end

end

app/models/competition_category.rb
class CompetitionCategory < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :competition
  has_many :event_athletes, :dependent => :destroy
  has_many :athletes, :through => :event_athletes
  validates_presence_of :name
  validates_presence_of :description
  validates_presence_of :competition_id
  
  after_create :create_event_athletes
  
  def ranked_results
    EventAthlete.ranked_and_categorized(self.id)
  end

  def <=>(other)
    name <=> other.name
  end

  private
  
  def create_event_athletes
    competition.athletes.each do |athlete|
      ea = EventAthlete.find_by_athlete_id_and_event_id(athlete.id, self.id)
      if !ea
        ea = EventAthlete.new(:athlete_id => athlete.id, :event_id => self.id)
        ea.save
      end
    end
  end

end

app/models/event_athlete.rb
class EventAthlete < ActiveRecord::Base
  belongs_to :athlete
  belongs_to :event
  validates_presence_of :athlete_id
  validates_presence_of :event_id
  
  before_save :result_to_score
  after_save  :update_rankings
  
  def name
    @name ||= "#{competition} / #{athlete.name} / #{event.name}"
  end
  
  def athlete_number
    @athlete_number ||= athlete.number
  end
  
  def competition
    @competition ||= event.competition.name
  end
  
  def self.ranked(event_id)
    close = EventAthlete.find_all_by_event_id(event_id, :order => :event_rank)
    no_rank, ranked = close.partition{|ea| ea.event_rank.nil? }
    (ranked + no_rank)
  end
  
  def self.ranked_and_categorized(event_id)
    EventAthlete.event_athletes_by_category(EventAthlete.ranked(event_id))
  end
  
  private
  
  def result_to_score
    score = result
    if result.to_s.split(":").size > 1
      score = EventAthlete.time_to_seconds(result)
    end
    self.score = score
  end

  def self.time_to_seconds(time_str)
    seconds = nil 
    split_str = time_str.to_s.split(":")
    if split_str.size == 3
      seconds =  (split_str[0].to_f * 60) + (split_str[1].to_f) + (split_str[2].to_f / 60)
    elsif split_str.size == 2
      seconds = (split_str[0].to_f) + (split_str[1].to_f / 60)
    end
    seconds
  end

  def self.sort_scores(event_athletes, lowest_wins = true)
    no_score, scored = event_athletes.partition{|e| e.score.nil? }
    sorted_by_score = scored.sort{|a,b| a.score <=> b.score}
    if lowest_wins
      (sorted_by_score + no_score)
    else
      (sorted_by_score.reverse + no_score)
    end
  end

  def soft_sort_by_rankings(unsorted_grouping)
    event = self.event
    lower_wins = event.rank_by_small
    EventAthlete.sort_scores unsorted_grouping, lower_wins
  end
  
  def self.event_athletes_by_category(event_athletes)
    categorized = {}
    event_athletes.each do |event_athlete|
      category = event_athlete.athlete.category
      if categorized[category]
        categorized[category] << event_athlete
      else
        categorized[category] = [event_athlete]
      end
    end
    categorized
  end
  
  def update_rankings
    if self.result_changed?
      event_athletes = event.event_athletes
      lower_wins = event.rank_by_small
      rankings = EventAthlete.event_athletes_by_category(event_athletes)
      rankings.each do |category,ea|
        update_ranked_group(EventAthlete.sort_scores(ea, lower_wins))
      end
      
    end
  end

  def update_ranked_group(sorted_grouping)
    previous_score_value = nil
    previous_rank = nil

    sorted_grouping.each_with_index do |ea, index|
      if same_scores(ea.score, previous_score_value)
        ea.event_rank = previous_rank
      else
        ea.event_rank = (index + 1) #index is zero based
      end
      ea.save
      
      previous_score_value = ea.score
      previous_rank = ea.event_rank
    end
    
  end

  
  def same_scores(score_a, score_b)
    if score_a.is_a?(Float) && score_b.is_a?(Float)
      score_a.round_to(12).eql?(score_b.round_to(12))
    else
      score_a.eql?(score_b)
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def competition
    @competition = Competition.find(params[:competition])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def leaderboard_ranking(athletes)
    rankings = []
    previous_rank_value = nil
    previous_rank = nil

    athletes.each_with_index do |athlete, index|
      rank = previous_rank
      tr = athlete.competition_rank_total
      if !same_scores(tr, previous_rank_value)
        rank = (index + 1) #index is zero based
      end
      rankings << [athlete, rank]
      
      previous_rank_value = tr
      previous_rank = rank
    end
    rankings
  end

  def same_scores(score_a, score_b)
    if score_a.is_a?(Float) && score_b.is_a?(Float)
      score_a.round_to(12).eql?(score_b.round_to(12))
    else
      score_a.eql?(score_b)
    end
  end


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wodleader</title>
  <script type="text/javascript" src="http://use.typekit.com/ufw0ggk.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <%= yield :page_specific_head_tags %>
  <style type="text/css">
    .blue {color: #004358;}
    .green {color: #1F8A70;}
    .yellow {color: #FFE11A;}
    .greenish {color: #99FF66;}
    .white {color: #FFF;}
    body { text-align: center; margin: 5em 0 0 0; vertical-align: middle; background-color:#004358; color: #FFE11A; font-family: adelle,serif; font-style: normal; font-weight: 100; font-size: 18px;} 
    .light {font-family: adelle,serif; font-style: normal; font-weight: 100;}
    pre {font-family: adelle,serif; font-style: normal; font-weight: 100;}
    a {text-decoration: none; color: #fff;}
    strong {color: #99FF66;}
    .content { width: 600px; text-align: left; margin: 0 auto; }
    .logo {font-size:32px;}
    h1 {font-size: 48px; margin-bottom:10px; }
    h2 {color: #FFF; font-size:32px;}
    h3 {color: #99FF66; font-size:24px;}
    li {list-style-type: none; margin-left:20px; font-family: adelle,serif; font-style: normal; font-weight: 100; font-size:24px; margin-top: 10px; margin-bottom:10px;}
    .athlete { margin-top: 10px; margin-bottom:20px; margin-left:20px; font-family: adelle,serif; }
    .rank { font-style: normal; font-weight: 100; font-size:36px; margin-right: 20px; }
    .athlete-info { font-style: normal; font-weight: 100; font-size:28px; }
    .pts { margin-left: 63px; font-size: 28px;}
    .small { font-size: 14px;}
    .info { font-size: 18px;}
    .tightbottom { margin-bottom: 0px;}
    .event-list-header { font-size: 22px; margin-top:30px; }
    .event-link { margin-left:20px; font-size:18px; margin-top:10px;}

    
  	a.button,
  	button,
  	input[type="submit"],
  	input[type="reset"],
  	input[type="button"] {
  		background: #eee; /* Old browsers */
  		background: #eee -moz-linear-gradient(top, rgba(255,255,255,.2) 0%, rgba(0,0,0,.2) 100%); /* FF3.6+ */
  		background: #eee -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(255,255,255,.2)), color-stop(100%,rgba(0,0,0,.2))); /* Chrome,Safari4+ */
  		background: #eee -webkit-linear-gradient(top, rgba(255,255,255,.2) 0%,rgba(0,0,0,.2) 100%); /* Chrome10+,Safari5.1+ */
  		background: #eee -o-linear-gradient(top, rgba(255,255,255,.2) 0%,rgba(0,0,0,.2) 100%); /* Opera11.10+ */
  		background: #eee -ms-linear-gradient(top, rgba(255,255,255,.2) 0%,rgba(0,0,0,.2) 100%); /* IE10+ */
  		background: #eee linear-gradient(top, rgba(255,255,255,.2) 0%,rgba(0,0,0,.2) 100%); /* W3C */
  	  border: 1px solid #aaa;
  	  border-top: 1px solid #ccc;
  	  border-left: 1px solid #ccc;
  	  padding: 4px 12px;
  	  -moz-border-radius: 3px;
  	  -webkit-border-radius: 3px;
  	  border-radius: 3px;
  	  color: #444;
  	  display: inline-block;
  	  text-decoration: none;
  	  text-shadow: 0 1px rgba(255, 255, 255, .75);
  	  cursor: pointer;
  	  margin-bottom: 20px;
  	  line-height: 21px;
  	}

  	a.button:hover,
  	button:hover,
  	input[type="submit"]:hover,
  	input[type="reset"]:hover,
  	input[type="button"]:hover {
  		color: #222;
  		background: #ddd; /* Old browsers */
  		background: #ddd -moz-linear-gradient(top, rgba(255,255,255,.3) 0%, rgba(0,0,0,.3) 100%); /* FF3.6+ */
  		background: #ddd -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(255,255,255,.3)), color-stop(100%,rgba(0,0,0,.3))); /* Chrome,Safari4+ */
  		background: #ddd -webkit-linear-gradient(top, rgba(255,255,255,.3) 0%,rgba(0,0,0,.3) 100%); /* Chrome10+,Safari5.1+ */
  		background: #ddd -o-linear-gradient(top, rgba(255,255,255,.3) 0%,rgba(0,0,0,.3) 100%); /* Opera11.10+ */
  		background: #ddd -ms-linear-gradient(top, rgba(255,255,255,.3) 0%,rgba(0,0,0,.3) 100%); /* IE10+ */
  		background: #ddd linear-gradient(top, rgba(255,255,255,.3) 0%,rgba(0,0,0,.3) 100%); /* W3C */
  	  border: 1px solid #888;
  	  border-top: 1px solid #aaa;
  	  border-left: 1px solid #aaa; }

  	a.button:active,
  	button:active,
  	input[type="submit"]:active,
  	input[type="reset"]:active,
  	input[type="button"]:active {
  		border: 1px solid #666;
  		background: #ccc; /* Old browsers */
  		background: #ccc -moz-linear-gradient(top, rgba(255,255,255,.35) 0%, rgba(10,10,10,.4) 100%); /* FF3.6+ */
  		background: #ccc -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(255,255,255,.35)), color-stop(100%,rgba(10,10,10,.4))); /* Chrome,Safari4+ */
  		background: #ccc -webkit-linear-gradient(top, rgba(255,255,255,.35) 0%,rgba(10,10,10,.4) 100%); /* Chrome10+,Safari5.1+ */
  		background: #ccc -o-linear-gradient(top, rgba(255,255,255,.35) 0%,rgba(10,10,10,.4) 100%); /* Opera11.10+ */
  		background: #ccc -ms-linear-gradient(top, rgba(255,255,255,.35) 0%,rgba(10,10,10,.4) 100%); /* IE10+ */
  		background: #ccc linear-gradient(top, rgba(255,255,255,.35) 0%,rgba(10,10,10,.4) 100%); /* W3C */ }

  	.button.full-width,
  	button.full-width,
  	input[type="submit"].full-width,
  	input[type="reset"].full-width,
  	input[type="button"].full-width {
  		width: 100%;
  		padding-left: 0 !important;
  		padding-right: 0 !important;
  		text-align: center; }
    
    .refresh {
      line-height: 10px !important;
      padding: 0px !important;
      margin-bottom: 0px !important;
    }
    .updated {
      margin-top: 5px;
      margin-left: 5px;
      position: absolute;
    }
    
    .blocky {
      background: #005858;
      -moz-border-radius: 5px;
  	  -webkit-border-radius: 5px;
  	  border-radius: 5px;
  	  padding: 10px;
    }
  </style>
</head>
<body class="content">
<div><span class="logo"><a href="/">Wodleader</a></span><br/><span class="light small">A multi-event crossfit scoring app by <%= link_to " Brian Doll", "http://emphaticsolutions.com"%>.<br/>Mobile friendly. Rock it.</span><hr/></div>
<%= yield %>

</body>
</html>

app/views/pages/competition.html.erb
<% competition = @competition%>
<h1 class="white"><%= competition.name %></h1>
<strong>When:</strong> <%= competition.when %><br/>
<strong>where:</strong> <%= competition.where %><br/><br/>
<p><%= competition.description %></p>


<div class="event-list-header">Skip to Event:</div>
<small>(These are not in order)</small>
<% competition.events.each do |event| %>
 <div class="event-link"><%= link_to event.name, "##{event.name}" %></div>
<% end %>

<a name="top"></a>
<h2 class="tightbottom">Current Leader Board:</h2>

<% if updated = competition.most_recent_stat_update %>
  <div class="greenish blocky">
    <%= link_to competition_url(competition), :class => 'refresh button' do %>
      <%= image_tag "reload.png", :width => '30' %>
    <% end %>
    <span class="updated">Stats updated <%= time_ago_in_words(updated) %> ago</span>
  </div>
<% end %>

<% competition.leader_board.sort.each do |category, athletes| %>
  <h4><%= category %></h4>
  <% leaderboard_ranking(athletes).each do |athlete, ranking| %>
    <div class="athlete">
      <span class="rank">#<%= ranking %></span>
      <span class="athlete-info"><%= "#{athlete.name}" %></span>
      <br/>
      <% max    = athlete.max_competition_ranking
         mine   = athlete.competition_rank_total
         points = (max.eql?(mine) ? "0" : mine)
      %>
      <span class="pts"><%= "#{points}" %>pts <span class="info"><%= " (##{athlete.number})" if athlete.number %><%= " from #{athlete.affiliation}" if athlete.affiliation %></span></span>
    </div>
  <% end %>
<% end %>
<br/>
<h2>Events:</h2>
<% competition.events.sort.each do |event| %>
 <a name="<%= event.name %>"></a>
  <h3><%= event.name %></h3>
  <small>[<a href="#top">Back to Leaderboard</a>]</small>
  <p><pre class="orange"><%= event.description %></pre></p>
  <% if !([1.0, 1, nil].include?(event.event_weight)) %>
    <p class="orange">This event is worth <%= (event.event_weight * 100).to_i %>%</p>
  <% end %>
    <% event.ranked_results.sort.each do |category, results| %>
      <h4><%= category %></h4>
      <% results.each do |result| %>
        <div class="athlete">
          <span class="rank">#<%= result.event_rank || 'X' %></span>
          <span class="athlete-info"><%= "#{result.athlete.name}" %></span>
          <br/>
          <span class="pts"><%= result.result %> <span class="info"><%= " (##{result.athlete.number})" if result.athlete.number %><%= " from #{result.athlete.affiliation}" if result.athlete.affiliation %></span></span>
        </div>
      <% end %>
    <% end %>
  <br/><br/>
<% end %>

app/views/pages/index.html.erb
<div class="tk-adelle">

<a href="#scoring">Curious how Crossfit games-style scoring works?</a>

<% Competition.all.reverse.each do |competition| %>
  <p>
  <h1><%= link_to "#{competition.name}  &raquo;".html_safe, competition_path(competition) %></h1>
  <strong>When:</strong> <%= competition.when %><br/>
  <strong>where:</strong> <%= competition.where %><br/>
  <p><%= competition.description %></p>
  </p>
<% end %>
  
  <a name="scoring"></a>
  <h3>How does Crossfit Games-style scoring work?</h3>
  <p>Athletes compete in events, resulting in a score. A score may be total number of reps, rounds, time, etc. Athletes are ranked against their group (RX Men, for example) for each event.  (Ties are ranked as expected, 1, 2, 2, 4, for example) The sum of an athlete's rankings is their total score for the competition.  The athlete with the lowest total score in each group is the winner.  3, 2, 1, GO!</p>

    

</div>